### ISSUE TITLE
Setting.SetEditable(false) Issues

### ISSUE THREAD

**Issue by Patrick-Seymour** [andrewgu/ModConfigMenu#21] opened 2016-04-26 04:54 UTC
Two issues with trying to disable a Setting field:

1) Seems weird, but it looks like the last Setting of a Group can't be SetEditable(false). It still appears brightly colored. If I disable groups of Settings anywhere else they seem to disable fine, but the last Setting of a Group doesn't change display at all.

2) Disabled settings are still editable. The change is visual only. Part of your doc says "Disabled settings look gray and aren't editable," so I assume that this is a bug and not intentional.

**Comment by andrewgu** [comment] 2016-04-27 22:30
Good catch. Looks like it'll need some sort of workaround unless I missed something important with using the built in "SetDisabled".

**Comment by andrewgu** [comment] 2016-04-29 03:57
Try again? It should properly disable now. Of course it goes with the nuclear option of just hiding everything... not ideal, but I can add showing the values while disabled back in for 1.1.

The problem is that UIMechaListItem.SetDisabled(...) does not work as advertised, so I'll have to re-implement the graying out behavior by guessing at the magical incantations to control the underlying Flash code.

**Comment by andrewgu** [comment] 2016-04-30 03:19
@Patrick-Seymour I also wasn't able to replicate the issue with the last setting in the group not changing, do you have a repro case I can work with?

**Comment by Patrick-Seymour** [comment] 2016-05-03 22:26
Here's what I'm setting, and the ModBuddy project. The last option doesn't disable properly. And as potentially noted from the slider issue, it might not GetValue() correctly.

https://www.dropbox.com/s/0h69k53eez1i6jk/mcm-disable-not-working.png?dl=0
https://www.dropbox.com/s/adw3g1301wr8jf9/TestMCMMod.zip?dl=1

**Comment by andrewgu** [comment] 2016-05-08 21:04
Quick update: I'm still on the road, will take a look when I'm back at my dev environment

**Comment by andrewgu** [comment] 2016-05-19 04:33
Going to close this ticket because it's working in my testing as of commit 1a19c18. However, I may wait to get other issues resolved before making an actual release to Steam/Nexus.

**Closed as completed by andrewgu** 2016-05-19 04:33 UTC
