### ISSUE TITLE
MCM Slider Option Subtracting 1

### ISSUE THREAD

**Issue by ghost** [andrewgu/ModConfigMenu#38] opened 2016-07-19 03:44 UTC
When trying to make a slider, sometimes the save appears to subtract one from whatever was selected. Can't reliably reproduce but happens more often than not. I know the save is the problem and not the load because the config file will have the wrong value in it after saving.

Have tried the ranges 0-30, 1-30, 0-20, and 1-20. I've also tried having the step parameter at 0 and 1. Issue appears to be more common on numbers not divisible by 3 but it's still not consistent. 

Have tested on 2 different sliders saving to 2 different options. One was an array element and one was a normal variable.

**Comment by andrewgu** [comment] 2016-07-19 06:23
Ok, can you try a specific snippet of code for me? 

There's a method attached to MCM_API_Slider:

```
function SetValueDisplayFilter(delegate<SliderValueDisplayFilter> Filter);
```

Here's it's signature:

```
delegate string SliderValueDisplayFilter(float value);
```

If you implement SliderValueDisplayFilter to just return a coerced string value:

```
slider.SetValueDisplayFilter(ConvertToString);
```

```
function string ConvertToString(float value)
{
    return string(value);
}
```

What label values do you see?

I suspect what's happening is that there is a rounding error issue. Getting more points of precision into the display might help confirm the problem.

If it's a rounding error, take a look at this bug's discussion about how the in-game slider has some... quirks. 

https://github.com/andrewgu/ModConfigMenu/issues/20

**Comment by andrewgu** [comment] 2016-07-19 06:24
Separate note: that function call lets you customize the number that gets displayed. The default implementation rounds to the nearest int, but it doesn't have to! ;)

**Comment by ghost** [comment] 2016-07-19 14:53
Pardon me on this, still new to unreal stuff, but where do I implement the SliderValueDisplayFilter function? Do I need to make a file somewhere and re-implement the entire interface or can I implement only that function or do I need to change and rebuild the MCM mod itself?

Also if it is just a rounding error, I can increase the range from 30 to around 700 as long as there is some way that I could change what values are actually displayed. The slider is for hours but for most people seeing it in days is easier.

**Comment by andrewgu** [comment] 2016-07-19 18:00
This might explain better than I can: https://udn.epicgames.com/Three/UnrealScriptDelegates.html

Basically the way it works is that MCM lets you change how the slider's value is displayed by calling `SetValueDisplayFilter` on it. By default, MCM rounds to the nearest integer (which is different from just calling `int(value)`), but you can override it for an individual slider by passing a delegate into it that points to a custom implementation.

I'm asking you to do it that way because it'll let you see the _actual_ value on the slider. I suspect what's happening is that "50" is getting turned into "49.99999992" or something.

**Comment by andrewgu** [comment] 2016-07-19 20:32
@Numbers33 If you send me a copy of your code I can tell you exactly what to write in. It should be pretty simple. If you don't want to share it publicly you can email me.

**Comment by ghost** [comment] 2016-07-20 13:30
I got it. It is using decimals and when I save it is always rounding down (thinking back on this it seems obvious. It's an int). So if I move the slider and set it to something like 12.9 then save and load, the value that is loaded is 12. Is the default label implementation rounding to the nearest integer instead of just truncating?

**Comment by andrewgu** [comment] 2016-07-20 21:33
Yup, the default implementation is set to round numbers to make the sliders work a bit more predictably. 

If you need to save an int, I recommend saving `int(value+0.5)` to round it to the nearest integer in your save handler.

**Comment by BlueRaja** [comment] 2016-07-20 21:36
Shouldn't the framework do that automatically?

**Comment by ghost** [comment] 2016-07-20 21:40
I think I'm just going to adjust the label to show the truncated number. That or I realized that spinners might be a little better than sliders. Gonna play around with it. Thanks for the help though. You rock.

**Comment by andrewgu** [comment] 2016-07-20 22:06
@BlueRaja I originally decided to not automatically convert to integer so that people who want floating point values can have them. I will probably redesign this for a future version so that this behavior is clearer up front.

@Numbers33 Sounds good, let me know if you need any more help. I'm going to close this issue, but please feel free to reopen if you want me to dig more into the numerical problem.

**Closed as completed by andrewgu** 2016-07-20 22:06 UTC

**Comment by Patrick-Seymour** [comment] 2016-12-12 07:10
Noticed this myself, and at first I though it was a bug in my own mod or MCM. I was quite surprised to hear that this was apparently intentional behavior! I can't help but feel as though this is definitely something that needs to be addressed and this bug reopened.

The issue isn't that MCM returns a float: It's twofold. It's that 1) the return value isn't snapped to the step size, and 2) that when converted to an int it represents a value different from the display. It shouldn't be the responsibility of a mod to perform conversions on the data being returned from the MCM slider.

Basically, anyone using an MCM slider right now has to either 1) know how the MCM slider is modifying the value to be used as part of its display (and perform the same modifications to reach the same displayed value), or 2) write their own display filter in order to make the slider display a different value. This process should be as simple as possible, and if the slider is going to be adjusting the display value it should perform the same adjustments to the return value as well.

I looked into this, found a couple of bugs with the vanilla XCOM2 implementation of its sliders, and implemented a couple of features into MCM. I'm going to make a pull request with my changes for review.
